Add with_errors() to response
MasoniteFramework/masonite4 pull request #125
Opened 2021-07-23 15:26 UTC by girardinsamuel

Fixes #117

2021-10-03 12:21 UTC, girardinsamuel commented
Not really satisfying but it's working now. The difficulty was that view was returning data and not response instance.
I think it should return response instance and getting data should be done in the response handler at the very end of the cycle.

This way we can always chain back(), redirect() with_input(), with_errors() ensuring we always have a valid response object.

2021-10-04 15:18 UTC, girardinsamuel commented on src/masonite/providers/RouteProvider.py
> +                data = route.get_response(self.application)
I am not really satisfied with that. It feels already like a patch...

2021-10-05 00:26 UTC, josephmancuso requested changes

2021-10-05 00:26 UTC, josephmancuso commented on src/masonite/providers/RouteProvider.py
> +                    isclass(data) and issubclass(data, ResponseFacade)
This looks really messy too .. Maybe we check for a method or attribute on the object?

2021-10-05 14:04 UTC, merged