add optional helper
MasoniteFramework/masonite4 pull request #87
Opened 2021-04-09 14:24 UTC by girardinsamuel

Add `optional` helper which can be useful to get attributes on model when we are not sure they exist.

```python
# if user has no profile yet, this won't raise an exception
optional(User.find(1).profile).avatar #== None

# default is configurable
optional(User.find(1).profile, default=False).is_verified #== False
```

It can works when using method but `is_method` should be set to `True` (I did not find a better way):
```python
optional(User.find(1).profile, is_method=True).create_avatar() #== None, won't raise an exception is user has no profile
```

2021-04-09 15:20 UTC, Marlysson commented
The trick using a internal class returning an object with metamethod was mindblow to me.

Awesome!!!

2021-04-12 02:51 UTC, josephmancuso requested changes

2021-04-12 02:51 UTC, josephmancuso commented on src/masonite/utils/helpers.py
> +    class OptionalWrapper(object):
Classes in Python 3 don't need to inherit the object class. This can be removed. 

```suggestion
    class OptionalWrapper:
```

2021-04-12 02:53 UTC, josephmancuso commented
This exists in M3. Is there a reason you rewrote this? I think the one in M3 takes into account the method thing. Maybe you can either port that one over or draw inspiration to how i did that

2021-04-12 02:57 UTC, josephmancuso commented
https://github.com/MasoniteFramework/masonite/blob/383cf4607700bfa442fa6bbf33c764035eee2fee/src/masonite/helpers/optional.py#L12

2021-04-12 07:38 UTC, girardinsamuel commented
> https://github.com/MasoniteFramework/masonite/blob/383cf4607700bfa442fa6bbf33c764035eee2fee/src/masonite/helpers/optional.py#L12

I did not check this was already available 😓 at least I have learned stuff on the way ! 😅 
So I will backport this instead.

2021-04-12 16:10 UTC, girardinsamuel commented
@josephmancuso I updated this helper with Masonite 3 code.
I just added a ability to provide a default value different from `None`

2021-04-16 02:00 UTC, josephmancuso approved these changes

2021-04-16 02:01 UTC, merged